version: '3.9'
services:
  music-service:
    image: musicimage
    container_name: musicservice
    build: BEJ_C2_S3_REST_API_MONGODB_MC_1/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8085:8085
    depends_on:
      - mongoService


  mongoService:
    image: mongo
    container_name: mongoservice
    ports:
      - 27017:27017
    networks:
      - mynetwork

  authentication-service:
    image: authenticationimagemusic
    container_name: authenticationContainermusic
    build: UserAuthentication/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8080:8080
    depends_on:
      - mysqlService


  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"


networks:
  mynetwork:
    driver: bridge
